extern print_espace
; Imprime une espace sur la sortie standard.

extern print_nl
; Imprime un saut de ligne sur la sortie standard.

extern read_int
; Lit un entier sur l'entrée standard
; et le met dans eax.
; Saute les caractères blancs.
; Renvoie 0 si l'entrée n'est pas un entier.

extern print_int
; Imprime le nombre contenu dans eax sur l'entrée standard.

extern print_string
; Affiche une chaine de caractères dont l'adresse est dans eax.



